### Linear Regression using sklearn module

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv('1.01. Simple linear regression.csv')

In [3]:
data

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [4]:
y=data['GPA']
x=data['SAT']

In [5]:
x.shape
x_mat=x.values.reshape(-1,1)
x_mat.shape

(84, 1)

In [6]:
y.shape

(84,)

In [7]:
reg=LinearRegression()

In [8]:
reg.fit(x_mat,y)

LinearRegression()

In [9]:
reg.score(x_mat,y)

0.40600391479679765

In [10]:
reg.coef_

array([0.00165569])

In [11]:
reg.intercept_

0.2750402996602803

In [12]:
 reg.predict([[1740]]) # SAT = 1740   ~ 3.2

array([3.15593751])

In [13]:
new_data=pd.DataFrame(data=[1700,1670],columns=['SAT'])
new_data

SAT
0  1700
1  1670

In [14]:
reg.predict(new_data)

array([3.08970998, 3.04003934])

In [15]:
new_data['predicted GPA']=reg.predict(new_data)
new_data

SAT  predicted GPA
0  1700       3.089710
1  1670       3.040039