In [1]:
import numpy as np

In [2]:
a= np.random.randn(3,3)
b= np.random.randn(3,1)

In [5]:
c= a*b
d= np.dot(a,b)

In [8]:
print(a)
print(b)
print(c)

[[-0.64205332 -1.50662363  0.77310164]
 [-0.2347351   1.42698041  1.18060614]
 [ 0.98017143 -0.88306117 -1.29773441]]
[[ 0.07934507]
 [-0.85964981]
 [-1.9264622 ]]
[[-0.05094376 -0.11954315  0.0613418 ]
 [ 0.20178999 -1.22670344 -1.01490785]
 [-1.88826321  1.70118396  2.50003628]]


In [6]:
d

array([[-0.24512613],
       [-3.51972161],
       [ 3.33693142]])

In [2]:
w=np.random.rand(4,3)
b=np.sum(w,axis=1,keepdims=True)

In [3]:
b.shape

(4, 1)

In [4]:
b

array([[1.78012314],
       [1.37456513],
       [1.28793644],
       [1.32778046]])

In [5]:
w

array([[0.67723941, 0.5309447 , 0.57193903],
       [0.34573472, 0.47013169, 0.55869872],
       [0.28129174, 0.6035843 , 0.4030604 ],
       [0.29763212, 0.05688887, 0.97325947]])