In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data=pd.read_csv('real_estate_price_size_year.csv')

In [4]:
data

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
..         ...      ...   ...
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

In [10]:
y=data['price']
x=data[['size','year']]

In [11]:
#standardization
from sklearn.preprocessing import StandardScaler

In [12]:
scaler=StandardScaler()

In [13]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
x_scaled=scaler.transform(x)
x_scaled
                         

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

In [15]:
#regression with scaled features
reg=LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
reg.coef_

array([67501.57614152, 13724.39708231])

In [17]:
reg.intercept_

292289.4701599997

In [20]:
#summary table
reg_summary=pd.DataFrame(data=[["Bias"],['size'],['year']], columns=["Features"])
reg_summary["Weights"]=reg.intercept_,reg.coef_[0],reg.coef_[1]
reg_summary                        

Features        Weights
0     Bias  292289.470160
1     size   67501.576142
2     year   13724.397082

In [21]:
#making predictions with std coefficients
new_data=pd.DataFrame(data=[[750,2017],[1240,2015]], columns=['size','year'])
new_data

size  year
0   750  2017
1  1240  2015

In [22]:
new_data_scaled=scaler.transform(new_data)

In [23]:
new_data_scaled

array([[-0.34752816,  0.93511251],
       [ 1.30537278,  0.51006137]])

In [24]:
reg.predict(new_data_scaled)

array([281664.62727465, 387404.47508464])