In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv('1.02. Multiple linear regression.csv')
data

SAT  Rand 1,2,3   GPA
0   1714           1  2.40
1   1664           3  2.52
2   1760           3  2.54
3   1685           3  2.74
4   1693           2  2.83
..   ...         ...   ...
79  1936           3  3.71
80  1810           1  3.71
81  1987           3  3.73
82  1962           1  3.76
83  2050           2  3.81

[84 rows x 3 columns]

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [4]:
y=data['GPA']
x=data[['SAT','Rand 1,2,3']]

In [5]:
reg=LinearRegression()

In [6]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [8]:
reg.intercept_

0.29603261264909486

In [11]:
reg.score(x,y)

0.4066811952814285

In [12]:
x.shape

(84, 2)

## adjusted R squared formula
$R^2{adj.}=1-(1-R^2)*\frac{n-1}{n-p-1}$

In [13]:
r2=reg.score(x,y)
n=x.shape[0]
p=x.shape[1]
adj_r=1-(1-r2)*(n-1)/(n-p-1)

In [14]:
adj_r

0.39203134825134023

## Feature Selection

In [15]:
from sklearn.feature_selection import f_regression 

In [16]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [17]:
p_values=f_regression(x,y)[1]

In [18]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [19]:
p_values.round(3)

array([0.   , 0.676])

## Summary Table

In [21]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=["Features"])
reg_summary["Coefficients"]=reg.coef_
reg_summary["P values"]=p_values.round(3)
reg_summary

Features  Coefficients  P values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676