### Question 1 (iii)

In [1]:
import numpy as np
add=[np.array([1,2,3]),np.matrix([[5,6],[7,8]]),[10,4,12]]
print(add)
add.pop(2) # removing the last element
add

[array([1, 2, 3]), matrix([[5, 6],
        [7, 8]]), [10, 4, 12]]


[array([1, 2, 3]),
 matrix([[5, 6],
         [7, 8]])]

### Question 1 (iv)

In [2]:
add=[np.array([1,2,3]),np.matrix([[5,6],[7,8]]),[10,4,12]]
print(add)
add[2]=[11,4,13,'a'] # updating the last element
print(add)

[array([1, 2, 3]), matrix([[5, 6],
        [7, 8]]), [10, 4, 12]]
[array([1, 2, 3]), matrix([[5, 6],
        [7, 8]]), [11, 4, 13, 'a']]


### Question 1 (ii)

In [6]:
N=3
arr1 = np.array([input().split() for _ in range(N)],int)
arr2 = np.array([input().split() for _ in range(N)],int)
print("arr1:",arr1.T)
print("arr2:", arr2.T)
print("sum:",np.add(arr1,arr2).T)

1
3
9
2
2
6
arr1: [[1 3 9]]
arr2: [[2 2 6]]
sum: [[ 3  5 15]]


### Question 1 (i) 

In [19]:
arr_num = np.empty(6, dtype=int)
arr_complex = np.empty(6, dtype = complex)
arr_char = np.empty(6,dtype = 'S3')
print(arr_num)
print(arr_complex)
print(arr_char)

[-966463472        605          0          0          1          0]
[1.28545352e-311+2.47032823e-322j 0.00000000e+000+0.00000000e+000j
 0.00000000e+000+1.31370903e-076j 7.17354251e-091+6.53029824e-042j
 1.26948713e-076+2.59983458e-056j 3.99910963e+252+2.02086079e-076j]
[b'\x10\xf0d' b'\xc6]\x02' b'' b'' b'' b'\x00\x01']


### Question 2 (i)

In [1]:
file = open("demo.txt", "r")
for line in file:
        print ("before sorting:", line.split(','))
        print ("after sorting:",sorted(map(int, line.split(','))))

before sorting: ['4', '6', '11', '5', '2', '108', '53', '9', '17', '21', '66']
after sorting: [2, 4, 5, 6, 9, 11, 17, 21, 53, 66, 108]


### Question 2(ii)

In [4]:
file=open("word_file.txt","r")
word_count=0
for line in file:
    words=line.split(" ")
    word_count += len(words)
print("number of words in file:",word_count)

number of words in file: 87


### Question 2(iii) 

In [5]:
file = open("word_file.txt","r")
distinct_word_count=0
for line in file:
    words=set(line.lower().split())
    distinct_word_count += len(words)
    #print(words)
print("number of distinct words in file:",distinct_word_count)

number of distinct words in file: 61


### Question 2(iv)

### Question 3

In [29]:
import numpy as np
import pandas as pd
dict1={'Name':['Alex','Mike','John','Dave','Joey'] ,'Height':[1.71,1.65,1.73,np.nan,1.82] ,'Test Score':[70.0,np.nan,84.0,62.0,73.0]}
       
df=pd.DataFrame(dict1)
df

Name  Height  Test Score
0  Alex    1.71        70.0
1  Mike    1.65         NaN
2  John    1.73        84.0
3  Dave     NaN        62.0
4  Joey    1.82        73.0

In [30]:
df.isnull()

Name  Height  Test Score
0  False   False       False
1  False   False        True
2  False   False       False
3  False    True       False
4  False   False       False

In [31]:
df.isnull().sum()

Name          0
Height        1
Test Score    1
dtype: int64

In [32]:
#df=df.replace(np.nan,'*')
df_1 =df.fillna('*')
df_1

Name Height Test Score
0  Alex   1.71         70
1  Mike   1.65          *
2  John   1.73         84
3  Dave      *         62
4  Joey   1.82         73

In [33]:
df_1['Test Score']=df['Test Score'].fillna('***')
df_1

Name Height Test Score
0  Alex   1.71         70
1  Mike   1.65        ***
2  John   1.73         84
3  Dave      *         62
4  Joey   1.82         73

In [36]:
df_2=df.copy()
df_2['Test Score'] = df_2['Test Score'].fillna(df_2['Test Score'].mean())
df_2

Name  Height  Test Score
0  Alex    1.71       70.00
1  Mike    1.65       72.25
2  John    1.73       84.00
3  Dave     NaN       62.00
4  Joey    1.82       73.00

In [38]:
df_3=df.copy()
df_3['Test Score'] = df_3['Test Score'].fillna(df_3['Test Score'].interpolate())
df_3

Name  Height  Test Score
0  Alex    1.71        70.0
1  Mike    1.65        77.0
2  John    1.73        84.0
3  Dave     NaN        62.0
4  Joey    1.82        73.0

In [42]:
df_4=df.copy()
df_4.dropna()

Name  Height  Test Score
0  Alex    1.71        70.0
2  John    1.73        84.0
4  Joey    1.82        73.0

### Question 4

In [ ]:
#a
#from random import seed
marks=[]
for i in range(20):
    marks.append(np.random.randint(0,2))

print(marks)
count=0
for i in marks:
    if i==1:
        count+=1
print(count)

sim = /20
print('probabilty of marks <=7 :', sim*100)

In [2]:
#b
import scipy.stats
ans= 1-scipy.stats.norm(67,13.7).cdf(79)
ans

0.19053882658339394

###  Question 5

In [6]:
from statistics import median
import pandas as pd

def LinReg(year,sales,new):
    mid = median(year)
    x=[]
    xy=[]
    x2=[]
    for i in year:
        x.append(i-mid)
    for i in range(len(sales)):
        xy.append(sales[i]*x[i])
        x2.append(x[i]**2)
    new_x=(new-mid)
    a= sum(sales)/len(year)
    b= sum(xy)/sum(x2)
    res = a+b*new_x
    return round(res)

year=[2005,2006,2007,2008,2009]
sales= [12,19,29,37,45]

LinReg(year,sales,2012)

70

In [7]:
import numpy as np
from sklearn.linear_model import LinearRegression

X=np.array([2005,2006,2007,2008,2009])
y=np.array([12,19,29,37,45])
x_mat= X.reshape(-1,1)
reg = LinearRegression()
reg.fit(x_mat,y)
reg.score(x_mat,y)

0.9977375565610798

In [8]:
reg.coef_

array([8.4])

In [9]:
reg.intercept_

-16830.399999999998

In [10]:
reg.predict([[2012]])

array([70.4])